### ISSUE TITLE
Opensearch error

### ISSUE THREAD

**Issue by cyb3n3tic** [idaholab/Malcolm#104]
Hi,

I am getting the errors below and not able to reach any dashboards post launch.

dashboards_1 [error][data][opensearch] [ConnectionError]: getaddrinfo ENOTFOUND opensearch opensearch:9200
dashboards_1 [error][data][opensearch] [ConnectionError]: connect ECONNREFUSED 172.18.0.3:9200

This is running in Eve-NG Pro within a Docker in Docker node

Any suggestions how to troubleshoot this please?

Appreciate any suggestions.

**Comment by mmguero** [comment]
Looks like the opensearch container failed to start. This is usually due to insufficient resources allocated to the container, most commonly memory. How much memory is on the system you trying to start up Malcolm on, and how much have you allocated to opensearch and logstash?

```
› grep JAVA_OPTS docker-compose.yml 
      OPENSEARCH_JAVA_OPTS : '-server -Xms16g -Xmx16g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'
      LS_JAVA_OPTS : '-server -Xms3g -Xmx3g -Xss1536k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'
```

Beyond that, running `doker-compose logs opensearch` a few minutes after startup and posting the result here could help us narrow it down.

**Comment by cyb3n3tic** [comment]
Interesting, that hadn't occurred to me, I had given it 4GB.
I will try an increase for that node now and may also resize the VM tomorrow (getting late here!)
Thanks, appreciated.

**Comment by mmguero** [comment]
Sure thing. OpenSearch is a bit of a memory hog. The minimum amount of memory I've been successful running Malcolm on is a system with about 12 GB (8 GB dedicated for opensearch, 2 GB for logstash, and 2 GB for the rest). The minimum "comfortable" system would be 16GB.

**Comment by cyb3n3tic** [comment]
Ah, right - I will report back tomorrow then, seems I have been way under provisioning!

**Comment by cyb3n3tic** [comment]
OK, so I have now upped the GCP instance to 24GB and given the Malcolm node 16GB. 
I still get  [error][data][opensearch] [ConnectionError]: connect ECONNREFUSED 172.17.0.7:9200

172.17.0.7 is on the bridge subnet but I can reach the upload dashboard on 172.29.129.38 which is eth0 but https://172.29.129.38 gives 502 Bad Gateway

I also get CryptographyDeprecationWarning along with Error processing command opensearch keystore: ['/usr/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated when running the start script - I have attached a snippet of this along with the opensearch logs if you'd be kind enought to have a look please.

[CryptographyDeprecationWarning.txt](https://github.com/idaholab/Malcolm/files/9091006/CryptographyDeprecationWarning.txt)
[Opensearch logs.txt](https://github.com/idaholab/Malcolm/files/9090970/Opensearch.logs.txt)

**Comment by cyb3n3tic** [comment]
I have also given opensearch 12GB and Logstash 4GB in the configs

**Comment by mmguero** [comment]
Hmmm okay interesting. Not exactly what I thought. Looks like what happened is that one of the files that gets created the first time you start Malcolm, even before the continers start, didn't get created but docker tried to mount it anyway (seeing this in opensearch.logs.txt, the bits about the opensearch.keystore file). Or it's possible that you tried to run something as root instead of the non-root user and the files got created with the wrong permissions?

We just need to clean things out a bit and I think we can get you underway. Do this in the malcolm directory:

* `./scripts/wipe`
* `sudo chown -R user:user ./*` (replacing `user` with our username)
* `rm -rf ./logstash/certs/logstash.keystore ./opensearch/opensearch.keystore`

Then try starting up again.

**Comment by cyb3n3tic** [comment]
Thanks for this, didn't solve the issue but I am rebuilding now to be sure I didn't make any obvious blunder!
Might be a separate issue but just kicked off docker-compose pull and getting /usr/lib/python3.9/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated "class": algorithms.Blowfish

**Comment by mmguero** [comment]
Not specifically a Malcolm thing, but I *think* that's [a warning that can be ignored](https://github.com/paramiko/paramiko/issues/2038).

**Comment by mmguero** [comment]
As far as that not solving the issue... if the errors about the `keystore` files are persisting, then they're not getting created during the startup. You're starting Malcolm by using the `./scripts/start` script, correct (vs. just doing your own `docker-compose up`), I assume? You could run startup with the `--verbose` and see the errors involved with the creation of the keystore files.

**Comment by cyb3n3tic** [comment]
Yep, using the start script. Certainly giving me the run around. 
As the services come up I see all up except for malcolm_opensearch_1          /usr/local/bin/docker-uid- ...   Exit 0
Initial verbose output prior to services coming up attached, anything jump out to you?
Also added post services up output
[initial startup.txt](https://github.com/idaholab/Malcolm/files/9095664/initial.startup.txt)
[Start verbose output.txt](https://github.com/idaholab/Malcolm/files/9095665/Start.verbose.output.txt)

**Comment by mmguero** [comment]
The issue is still this line:

```
opensearch_1         | Exception in thread "main" java.io.IOException: Is a directory: NIOFSIndexInput(path="/usr/share/opensearch/config/opensearch.keystore")
```

The other thing I see that looks weird to me is this `'1000:1000-w'` string I'm seeing in the verbose log. Looking in your compose file, are you seeing that `1000-w` at the top in the PGID variable? Also the fact that it's running `docker-compose exec` instead of `docker-compose run` with the verbose start makes me thing maybe something's not getting shut down all the way?

Let's try this (in the Malcolm directory):

* shut everything down again with `./scripts/wipe`
* verify no Malcolm-related containers are running/left behind with `docker ps -a`; if they are, do a `docker stop` or whatever to kill them
* let's double check and make sure there are no files/directories not owned by your user: `find . \( ! -user $(id -u) -o ! -group $(id -g) \) -exec ls -l "{}" \;`
* if there are any, chown them so they're owned by your uid/gid
* look at the keystore files, if they exist: `find . -name "*.keystore" -exec ls -l "{}" \;`
* if they do, forcibly remove them (whether they are files or directories)
* check the `PUID` and `PGID` values in your compose file: `grep -P "(P.ID)" docker-compose.yml`
* if they are anything other than the numeric values matching your user and group, fix that
* then try starting things back up

I'm convinced this something local that got into a weird state and we just need to figure out the right way to clean up whetever happened.

**Comment by cyb3n3tic** [comment]
I have an entry for volumes as below,
    volumes:                                                                                                                                      
      - ./opensearch/opensearch.keystore:/usr/share/opensearch/config/opensearch.keystore:rw
Does that look correct to you?

And I have x-process-variables: &process-variables
  # docker containers will run processes as unprivileged user with UID:GID
  PUID : 1000
  PGID : 1000

I ran all the suggested and all came up clear

Apologise for this dragging out! Appreciate the input and appreciate you are probably out of ideas / patience

**Comment by mmguero** [comment]
Yes, that looks correct. And upon startup, that `./opensearch/opensearch.keystore` should be created (as well as the logstash one I've referenced a few times) prior to any other Malcolm containers starting up so that when docker starts them that file bind mount works (and is not created as an empty directory owned by root, which is what is happening right now as is what happens when a bind mount is performed on a file that doesn't exist). So when you ran the `find . -name "*.keystore" -exec ls -l "{}" \;` command, what was returned? Nothing? empty directories? empty files?

I'm not familiar with the environment you're on, and not to dissuade you from continuing to try to figure out what you're doing, but if you'd prefer a VM route you could just install the Malcolm linux image from the installer ISO which should pretty much have everything preconfigured. [ISO download](https://malcolm.fyi/download/) and [instructions](https://malcolm.fyi/documentation/#ISOInstallation)

**Comment by cyb3n3tic** [comment]
Yeah, total 0 total 0
ISO route certainly worth a look at this stage - I don't think I am going a particularly common route with this.
If I'm feeling keen I'll have another go at this method in the future, just because....

I will reply back and close with comment when I am finally up and running - hopefully soon!

Thanks again.

**Comment by mmguero** [comment]
The ISO images should take maybe 3-5 minutes to load. Memory requirements should be the same (16+ GB). Disk space really is more about how much storage you want for PCAP/indices... for the OS and Malcolm itself without any of your data the whole system would be fine with maybe like 40 gigs or something, but of course you'll want more for your data.

Actually one thing you could run into if it failed loading the docker images if you didn't have a ton of disk space (and if you're doing it in a VM) could have been which option you chose during install. There's an ISO installer option for `Virtual Machine Single Partition Quick Install` which won't try to parcel everything out into different partitions and is probably the best choice for a VM.

**Comment by cyb3n3tic** [comment]
Despite all your helpful input I have not made any headway - I did get a build completed using the ISO with 60 gig disk however this eventually gave me the same opensearch enotfound 9200 errors. It must be due to how Eve-NG handles networking / docker - not sure but I'm going to look at running Malcolm outside of Eve-NG and connect to it that way instead.

Thanks again.
