### ISSUE TITLE
Arkime_1 - Waiting for WISE to start

### ISSUE THREAD

**Issue by cyb3n3tic** [idaholab/Malcolm#113]
I have Malcolm running on a 16GB Ubuntu instance in GCP and seeing the error below when running the start script.

arkime_1             | curl: (7) Failed to connect to 127.0.0.1 port 8081: Connection refused
arkime_1             | Waiting for WISE to start

Any suggestions on what to check at this stage please. I ensured that I installed and then ran with a non root user, permissions seem correct but clearly I have missed something!

I can access https://10.132.0.4/upload and https://10.132.0.4/name-map-ui only at present

**Comment by mmguero** [comment]
Not quite enough information for me to take a guess there... that particular "error" message can show up while wise is starting (but hasn't started yet) and may resolve itself.

My best guess is one or more containers failed to start, possibly because of resource allocation. We could debug by getting the output of the following commands, while it's in this broken state after trying to start up (run these in the Malcolm directory):

* `docker ps -a`
* `grep JAVA_OPTS docker-compose.yml`
* `docker-compose logs opensearch`

Let's start there.

**Comment by cyb3n3tic** [comment]
Hi. The initial VM spec was 8GB but this was increased to 16GB however I had forgotton to set the memory in docker-compose.yml but set it to 10Gb today. Still struggling but not seeing WISE errors so you were spot on with that.
I have now increased the memory for the VM to 24Gb but left docker-compose as is for the moment.

OPENSEARCH_JAVA_OPTS : '-server -Xms10g -Xmx10g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'
LS_JAVA_OPTS : '-server -Xms4g -Xmx4g -Xss1536k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'

Docker ps -a output and opensearch logs attached, thanks.

[docker-compose logs opensearch.txt](https://github.com/idaholab/Malcolm/files/9282570/docker-compose.logs.opensearch.txt)
[Docker ps -a.txt](https://github.com/idaholab/Malcolm/files/9282571/Docker.ps.-a.txt)
.

**Comment by mmguero** [comment]
The issue seems to be something to do with the ownership/permissions of some of the files/directories under the Malcolm installation directory (looking at the docker-compose logs output from opensearch). Should be easy enough to fix up.

First, let's make sure the UID/GID we're running malcolm with matches yours. Run `id -u` and `id -g` as your normal, non-root user. Then look in your `docker-compose.yml` file near the top, at the PUID and PGID environment variables. Do they match? If not, change the values in the yml file and save it.

Then, in a terminal, navigate to the Malcolm directory run the following to stop/wipe malcolm, fix the permissions, clean up anything that got created with bad permissions:

* `cd ~/Malcolm` (or wherever you installed it to)
* `./scripts/wipe`
* `sudo chown -R $(id -u):$(id -g) *`
* `./scripts/wipe`

Then you should be able to run `./scripts/start again and hopefully things will come up better.

If that doesn't work, I'd suggest blowing away the entire Malcolm directory and starting over, but this time make sure when you run the `./scripts/install.py --configure` you put in the right values for PUID and PGID.

**Comment by cyb3n3tic** [comment]
Thank you sir, thanks to your advise I now have this running perfectly - I can't thank you enough.
My UID was different to that stated in docker-compose.yml so I changed it there and then carried out the wipe, chown and wipe steps. I had previously wiped and chowned but hadn't spotted the UID issue.
Now to feed it some data......
Have a great day, I will!
