### ISSUE TITLE
OpenSearch connection error 400

### ISSUE THREAD

**Issue by cyb3n3tic** [idaholab/Malcolm#117]
Hi,

I have hedgehog sensor running but I am struggling to configure forwarding to Malcolm, the error I receive when configuring/testing a forwarding interface is as below;

Opensearch connection error 400
Connection error:
Error: [Errno 111] Connection refused

Have I missed out some configuration in Malcolm perhaps?

Thanks in advance for any advise.

**Comment by mmguero** [comment]
First, check your system's firewall. To forward from Hedgehog to Malcolm you're going to want to make sure ports 9200/tcp and 5044/tcp are open. If you're using the ISO installed version of Malcolm this should already be the case (you could double-check by running `sudo ufw status`). If you're running Malcolm in docker on your own system check your documentation for `ufw`, `iptables`, etc. to make sure these ports are open.

The second thing to check is during Malcolm's `install.py --configure` step. There are a couple of questions here:

```
Expose OpenSearch port to external hosts? (y/N): y

Expose Logstash port to external hosts? (y/N): y
```

The defaults to these are `n` but you should answer `y`.

Doing so will make sure that these lines in your docker compose file ([here](https://github.com/idaholab/Malcolm/blob/c2c3df0b71a2c71c1fa93ebd2a37d609accf8573/docker-compose.yml#L918) for opensearch, [here](https://github.com/idaholab/Malcolm/blob/main/docker-compose.yml#L434) for logstash) read `0.0.0.0` instead of `127.0.0.1`.

**Comment by cyb3n3tic** [comment]
Thanks for the suggestions, all points covered but still getting error 400, most odd. I'll investigate further, tcpdump has yet to cast any light!

**Comment by mmguero** [comment]
Please reopen if you find something going on in Malcolm itself, I suspect if's something local to your system.

**Comment by cyb3n3tic** [comment]
For the record, I finally solved this with the below
iptables -A PREROUTING -t nat -i ens4 -p tcp --dport 9200 -j DNAT --to 172.18.0.11
iptables -A FORWARD -p tcp -d 172.18.0.11 --dport 9200 -j ACCEPT
