### ISSUE TITLE
Nmap scan results

### ISSUE THREAD

**Issue by robcarson8** [idaholab/Malcolm#153]
I was running some tests to see which Nmap scans were picked up by Malcolm within my network.

-sn --- No
-v ---Yes
-sV --- Yes
-sT --- No
-sS --- Yes
-O --- No

I found it strange that -sT was picked up, but -sS was not.
I have also found that my results differ slightly each time I run these tests.

Please can you advise?

**Comment by mmguero** [comment]
I believe the only plugin we've got in Malcolm that's handling scan detection is [ncsa/bro-simple-scan](https://github.com/ncsa/bro-simple-scan), which is what we've had in place the last version or two since Zeek's built-in scan.zeek now is listed as [deprecated](https://github.com/zeek/zeek/blob/21a78816e9d6cd1b7708cb0346b42841b3c3e331/scripts/policy/misc/scan.zeek#L7).

I'd recommend checking the information for that plugin. Malcolm's not doing anything special with that plugin other than enabling it. It might be that the notice repeat suppression code (which is, by default, set to one hour) would give you different results if you are running scans more frequently than that.
