### ISSUE TITLE
Arkime: Error talking to node

### ISSUE THREAD

**Issue by EugeneFenko** [idaholab/Malcolm#219]
Hello, when I open any rows in Arkime, packet data from remote Hedgehog sensor not show, but show error `Error talking to node..check viewer logs`.

```
ERROR - Couldn't proxy request= URL {
    href: 'https://10.0.0.100:8005/api/session/sensor/3@230623-3CQyUDw6wkpPkqPEB6iPKDb4/packets?base=natural&line=false&image=true&gzip=false&ts=false&decode=%7B%22BODY-UNBASE64%22:%7B%7D%7D&packets=500&showFrames=false&showSrc=true&showDst=true',
    origin: 'https://10.0.0.100:8005',
    protocol: 'https:',
    username: '',
    password: '',
    host: '10.0.0.100:8005',
    hostname: '10.0.0.100',
    port: '8005',
    pathname: '/api/session/sensor/3@230623-3CQyUDw6wkpPkqPEB6iPKDb4/packets',
    search: '?base=natural&line=false&image=true&gzip=false&ts=false&decode=%7B%22BODY-UNBASE64%22:%7B%7D%7D&packets=500&showFrames=false&showSrc=true&showDst=true',
    searchParams: URLSearchParams {
      'base' => 'natural',
      'line' => 'false',
      'image' => 'true',
      'gzip' => 'false',
      'ts' => 'false',
      'decode' => '{"BODY-UNBASE64":{}}',
      'packets' => '500',
      'showFrames' => 'false',
      'showSrc' => 'true',
      'showDst' => 'true' },
    hash: ''
  }
  error= Error: write EPROTO 140601317922752:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
```

I check logs, and it look like this error: [Issue](https://github.com/elastic/elasticsearch-js/issues/1009)

What a Malcolm config can be edited for setup HTTP and fixed it?

**Comment by mmguero** [comment]
When you say setup for HTTP, I'm not sure I understand. Malcolm is set up by default so that the Arkime viewer on the Malcolm server and the Arkime viewer process running on Hedgehog are both using TLS with self-signed keys.

On the Hedgehog side, under `/opt/sensor/sensor_ctl`:

* [the relevant lines from `control_vars.conf`](https://github.com/idaholab/Malcolm/blob/f76acfbcbe0a3b99c9ce033c088a649d0129cb7e/sensor-iso/interface/sensor_ctl/control_vars.conf#L20-L22)
* [Arkime viewer being started on Hedgehog](https://github.com/idaholab/Malcolm/blob/f76acfbcbe0a3b99c9ce033c088a649d0129cb7e/sensor-iso/interface/sensor_ctl/supervisor.d/arkime.conf#L9-L10) to use TLS
* [the code on Hedgehog that runs prior to Arkime starting that generates the TLS keys](https://github.com/idaholab/Malcolm/blob/f76acfbcbe0a3b99c9ce033c088a649d0129cb7e/sensor-iso/interface/sensor_ctl/supervisor.init/arkime_config_populate.sh#L77C30-L89)

Arkime itself on the Malcolm side also uses TLS to talk to its own local instance of viewer:

* [initarkime.sh](https://github.com/idaholab/Malcolm/blob/f76acfbcbe0a3b99c9ce033c088a649d0129cb7e/arkime/scripts/initarkime.sh#L22-L33) where the certs are generated
* [config.ini](https://github.com/idaholab/Malcolm/blob/f76acfbcbe0a3b99c9ce033c088a649d0129cb7e/arkime/etc/config.ini#L27-L28) where it indicates to use the TLS key/cert

Used by both:

* [self_signed_key_gen.sh](https://github.com/idaholab/Malcolm/blob/main/shared/bin/self_signed_key_gen.sh) to generate the key/cert file(s)

As far as I know you cannot set up Arkime to use TLS with one viewer (e.g., its own local viewer) and non-TLS with the other (Hedgehog or another Arkime viewer instance).

So I think the issue is on the hedgehog ensure that the TLS keys are being generated correctly. If you really want to use unsecured non-TLS HTTP communications, you'd have to modify both the Hedgehog to not specify the key/cert file for viewer, AND you'd have to change `config.ini` on the Malcolm side to not specify the certFile and keyFile. Which would mean having a local copy of `config.ini` and using a [Docker bind mount](https://idaholab.github.io/Malcolm/docs/contributing-local-modifications.html#Bind) to mount that local modified file to `/opt/arkime/etc/config.ini`. That's not a recommended configuration, it would be preferred to use secure communications.

**Comment by EugeneFenko** [comment]
Thanks for the answer, of course I prefer to use a secure connection. 
What are the possible steps to solve this problem?

**Comment by mmguero** [comment]
This normally all happens automatically without you having to do anything specific. I'm assuming you're using the latest release of Malcolm and have gone through all the steps of the [end-to-end guide](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample). You've gone through the configuration for [both the Malcolm side](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#MalcolmConfig) and the [Hedgehog side](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#HedgehogConfigForwarding)?

Do the cert and keyfile exist at /opt/sensor/sensor_ctl/arkime?

**Comment by EugeneFenko** [comment]
Yes, I set everything up correctly and it used to work fine until one day I got this error when opening the package.

Well, I checked the directory you mentioned and the `viewer.crt/key` certificates are missing.

Now I have only two questions:
1. Why did the certificates disappear? It is obvious that they were present before
2. How to create them again?

Thanks for the help @mmguero

**Comment by mmguero** [comment]
Those files *should* get recreated everytime Arkime tries to start up on the sensor. So doing a reboot, or,

* /opt/sensor/sensor_ctl/shutdown
* /opt/sensor/sensor_ctl/supervisor.sh

Those two commands should cause them to be recreated.
