### ISSUE TITLE
ISO installers result in blank screen when booting with BIOS

### ISSUE THREAD

**Issue by rhandorf** [idaholab/Malcolm#26]
Greetings,

when building hedgehog, there are no obvious errors during the generation of the ISO, however when installing it on a host, it attempts to install Debian, and then fails with a blank screen (no video output) after installing grub. The resulting install does not boot at all.

ISO built on a host using Ubuntu 18.0.4, vagrant 2.2.10, and VirtualBox 5.2.42.

**Comment by mmguero** [comment]
My guess is that your virtualbox VM is set to BIOS boot for the firmware, instead of EFI boot. At the current time the ISO works correctly with EFI but has issues with BIOS. Try switching it to EFI and reinstall and come back with the results.

Either way, I'll probably leave this issue open to track the BIOS boot issue.

**Comment by rhandorf** [comment]
Thank you- that was it. I missed the comment in the docs.
