### ISSUE TITLE
Suricata/ Zeek logs and alerts not shown in Arkime dashboard

### ISSUE THREAD

**Issue by e101sg** [idaholab/Malcolm#273]
[Using](url) Malcolm on top of Ubuntu 22.04, during install i have enabled Zeek /Suricata logs/custom rules alert as a default. After restart of the Malcolm i can not see Zeek logs and Suricata logs or alert is not showing in the Arkime Dashboard.  Malcom Version **23.05.01**  How to restart the Suricata alone or Zeek alone? or where to check, whether Zeek and Suricata installed correctly. I can not see any Suricata folder in  `/opt/` for example `/opt/suricata/rules` or `suricata.yaml ` anywhere in my Ubuntu directory.
Am i missing somethings..Please advise.Screenshot of   `./scripts/status`
![malcom_status](https://github.com/idaholab/Malcolm/assets/1925934/f3cc6751-cfe3-4c89-a251-98687fb1abe5)

Cheers!
Chandra

**Comment by mmguero** [comment]
You're not going to see anything in `/opt` in your host system since all of that is mounted into the docker containers. Let's check a few things to make sure you've got things enabled correctly. Run the following commands and share the output here:

* `cat config/suricata*.env`
* `cat config/zeek*.env`
* `cat config/pcap-capture.env`

**Comment by e101sg** [comment]
Here it is ...
`cat config/suricata*.env`
[
![Suricata_1](https://github.com/idaholab/Malcolm/assets/1925934/0725047f-6722-4be3-9f3a-65be8bfc86f5)
](url)
`cat config/zeek*.env`
[
![Zeek_settings_1](https://github.com/idaholab/Malcolm/assets/1925934/61a5471c-fc5f-4e15-8f3d-dbb9423cbef7)
![Zeek_settings_2](https://github.com/idaholab/Malcolm/assets/1925934/5bf20d69-3c91-42f0-ad08-d9061cfde844)
](url)
`cat config/pcap-capture.env`
![Zeek_settings_3](https://github.com/idaholab/Malcolm/assets/1925934/d110eac4-3645-4c7c-a9ce-6fab06e1d341)

**Comment by e101sg** [comment]
I am getting the like this output.. not sure what it means?

![Screenshot from 2023-10-31 15-06-39](https://github.com/idaholab/Malcolm/assets/1925934/257c5ab3-a12b-4f3e-b8b0-265e947e64e2)

**Comment by mmguero** [comment]
Okay what that's telling me is that indeed Arkime is capturing traffic and logging it correctly (the "doc_count":7704501, "key": "arkime" bit) but we're not getting any data from Zeek or Suricata at all.

But having looked at the .env files up above, I can't see why that would be.  I think to debug this further I'm going to need to see some logs to see if I can figure it out, but I don't think screenshots are going to be the best way to do it as they might be a little bit long.

Run this command in the Malcolm directory:

```
docker-compose logs filebeat suricata suricata-live zeek zeek-live logstash > malcolm_debug_logs.txt
```

Then send me that file. Rather than post it here, email it to malcolm@inl.gov and just mention this issue number and I'll take a look at it there.

**Comment by e101sg** [comment]
Hi Seth, 
yes, i can execute the above command but it took long time complete; in the end it is size is huge ...it is **around 6GB.** Not sure,why?  Because of this huge file, my Ubuntu VM has less disk space.  So, afraid i can not send the file. 
Any thoughts? Thanks.

Cheers!
Chandra

**Comment by mmguero** [comment]
I'm not sure, but I would recommend starting over with the latest version of Malcolm and follow the quickstart guide as closely as you can. Then see if you're getting the same issue. Good luck.
