### ISSUE TITLE
investigate integrating sandialabs/gait Zeek plugin

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#418]
A colleague sent me this link, we should see if it would make a good fit for Malcolm

[sandialabs/gait](https://github.com/sandialabs/gait)

**Comment by piercema** [comment]
A review of the tool shows that it is relatively new. It provides a few additional metrics focused on profiling endpoints and proxies. Although it can add interesting data this data isn't central to Malcolm's goals. Due to limited development time, we will not be pursuing integrating this but users are welcome to integrate this plugin independently.
