### ISSUE TITLE
how to build and start docker container using docker images

### ISSUE THREAD

**Issue by kirankalelkar** [idaholab/Malcolm#438]
Dear Team,
I am tried but i am unable to up the docker conatiner. this is my request please add the updated configuration setting in README.md file. How to build and start container using docker images.

**Comment by mmguero** [comment]
The documentation you're looking for can be found here in the [Quick start](https://idaholab.github.io/Malcolm/docs/quickstart.html) guide, or in this [installation example using Ubuntu](https://idaholab.github.io/Malcolm/docs/ubuntu-install-example.html#InstallationExample).

As the instructions say, you'll need to run `./scripts/configure` to configure Malcolm, `./scripts/auth_setup` to configure authentication, and then `docker compose --profile malcolm pull` will pull the images (depending on how you have Docker installed, you may need to run `docker-compose` instead of `docker compose`, if that command fails).

**Comment by kirankalelkar** [comment]
i have tried but no luck when i run the ./scripts/auth_setup getting below error.
**Exception: auth_setup should not be run as root**

please check below screenshot for your referance.
![malcolm fail 1](https://github.com/idaholab/Malcolm/assets/163304329/d311eef5-31d7-41ef-ae52-be5122272c48)
