### ISSUE TITLE
Unable to run ./start script in Malcolm

### ISSUE THREAD

**Issue by HeroS3c-new** [idaholab/Malcolm#513]
When trying to run the ./start script located in the /Malcolm/scripts directory, I am encountering the following exception:
text
`Exception: start requires docker, please run install.py
`
This is despite having Docker installed on my system. I have checked the following:
The ./start script has the correct execution permissions.
I have reviewed the Malcolm documentation, but could not find any additional configuration steps that I may have missed.
I have tried running the install.py script as suggested by the error message, but the issue persists.
Could you please help me understand what might be causing this problem and provide any guidance on how to resolve it? I would greatly appreciate your assistance in getting the Malcolm project set up and running correctly on my system.

**Comment by mmguero** [comment]
What happens if you run `docker info` as the non-root user (i.e., the user that's running Malcolm, with the UID/GID that you specified during configuration that ended up in `./config/process.env`)?

If you get an error there, it could be that you either didn't get added to the `docker` group (running `id` ought to tell you that) or you did get added to the `docker` group but the system hasn't been rebooted for that to take effect.

**Comment by HeroS3c-new** [comment]
You right! Just solved.
