### ISSUE TITLE
Why is there no configuration in Malcolm to enable real-time capture of Arkime on demand

### ISSUE THREAD

**Issue by alleniverson33** [idaholab/Malcolm#537]
I want Arkime to capture traffic in real-time. Is there any good recommendation method？

**Comment by mmguero** [comment]
The reason that Arkime can't capture "on demand" in a Malcolm standalone installation is due to its necessity to communicate with the internal OpenSearch instance and at the same time listen on the interface provided to it in "host" network mode. I'm not aware of a way to configure it to be able to do both of those things using Docker.

There are a few options for running live Arkime capture:

* Malcolm's network sensor OS [Hedgehog Linux](https://idaholab.github.io/Malcolm/docs/hedgehog.html) runs Arkime capture to [capture live traffic](https://idaholab.github.io/Malcolm/docs/live-analysis.html#Hedgehog) and forwards the traffic metadata to Malcolm in real-time.
* A separate capture-only instance of Malcolm in the [hedgehog run profile](https://idaholab.github.io/Malcolm/docs/live-analysis.html#Profiles) can forward to another Malcolm instance's OpenSearch database
* Running Malcolm with a [remote OpenSearch or Elasticsearch](https://idaholab.github.io/Malcolm/docs/opensearch-instances.html#OpenSearchInstance) instance rather than its internally-managed one will give you the option to run Arkime capture live.

I'm not aware of any other way to run Arkime's capture tool live in a Malcolm standalone installation due to the constraint I listed in the first paragraph.

**Comment by mmguero** [comment]
See discussion here: cisagov/Malcolm#328

**Comment by alleniverson33** [comment]
> The reason that Arkime can't capture "on demand" in a Malcolm standalone installation is due to its necessity to communicate with the internal OpenSearch instance and at the same time listen on the interface provided to it in "host" network mode. I'm not aware of a way to configure it to be able to do both of those things using Docker.
> 
> There are a few options for running live Arkime capture:
> 
> * Malcolm's network sensor OS [Hedgehog Linux](https://idaholab.github.io/Malcolm/docs/hedgehog.html) runs Arkime capture to [capture live traffic](https://idaholab.github.io/Malcolm/docs/live-analysis.html#Hedgehog) and forwards the traffic metadata to Malcolm in real-time.
> * A separate capture-only instance of Malcolm in the [hedgehog run profile](https://idaholab.github.io/Malcolm/docs/live-analysis.html#Profiles) can forward to another Malcolm instance's OpenSearch database
> * Running Malcolm with a [remote OpenSearch or Elasticsearch](https://idaholab.github.io/Malcolm/docs/opensearch-instances.html#OpenSearchInstance) instance rather than its internally-managed one will give you the option to run Arkime capture live.
> 
> I'm not aware of any other way to run Arkime's capture tool live in a Malcolm standalone installation due to the constraint I listed in the first paragraph.

Okay, I understand. Thank you
